### ISSUE TITLE
URGENT: Push Notification Tokens aren't active until the user views the Dialog List

### ISSUE THREAD

**Issue by hagitmer** [Hacknocraft/AppFriendsAndroidCore#10] opened 2017-01-24 18:35 UTC
We have the call to register the Firebase token set up and the subscriber gets a `true` value in its onNext, but when I hide the app and send a message to that user, there’s no push notification delivered.  Whats strange is that once we actually navigate to the messages screen (the dialog list) in the app, then hide the app and send a message to that user, the notification gets delivered.  I added a breakpoint in the registration code, and it is getting called on initial login, not when the user views the dialog list, so it seems like there is something happening inside the SDK that is causing this delay in registering the Firebase token.

**Comment by hagitmer** [comment] 2017-01-25 16:04
Hi @laeroah. Just an FYI, this is a release blocker for us so wanted to get your input on the ETA.

Thanks!

**Comment by laeroah** [comment] 2017-01-25 16:15
@hagitmer we couldn't reproduce this on our end, so we are still investigating. We did make a mistake in the last release to always return true at the subscriber. This will be fixed next release.
Just to make sure it is really registered, could you check if SDK initialization and user login to AF has completed when register push is called? I remember on iOS the initialization caused quite a bit issues.

**Comment by nrschultz** [comment] 2017-01-25 17:40
Hey @laeroah we are waiting for AppFriends login to complete before posting the Firebase token to AF, would login work without the SDK being initialized? 

 Also the extremely strange part is that just by displaying the DialogListFragment on the screen, push notifications start working, the token registration code isn't getting called again when that fragment gets displayed, but it does seem like thats what it takes to get the registration to work.

**Comment by laeroah** [comment] 2017-01-25 17:42
@nrschultz hey, login should not work if initialization wasn't complete. Let's wait till our next release when we can properly return registration result to you. It will make whatever problem apparent to us. Sorry for the wait, but this should be an easy fix once we know what the problem is.

**Comment by nrschultz** [comment] 2017-01-25 17:45
Ok, sounds good, when do you think that release will be?

**Comment by laeroah** [comment] 2017-01-25 17:45
we will make one by tmr.

**Comment by nrschultz** [comment] 2017-01-25 17:46
👍

**Comment by laeroah** [comment] 2017-01-27 11:22
This one took a long time to find, but what happens is that once logged in, the sdk will monitor the app for foreground/background status of the activities in order to let the server know when to send push messages or not. the monitor is set up by a separate executor pool during login so that login is not blocked and the client app can continue on. What could have happened is that the client app has already gotten onto an activity before the monitor could attach, so only navigating to another activity activates the monitor and thus push. We made changes so that the monitor will attempt to attach to already loaded activities for background states as well.

**Comment by laeroah** [comment] 2017-01-27 20:25
should be fixed by 3.0.6 release

**Closed** 2017-01-28 16:39 UTC
Labels: bug

**Comment by HacknocraftDev** [comment] 2017-09-03 00:32
This issue was moved to Hacknocraft/AppFriendsAndroidCore#11
